apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-leader-elector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-leader-elector
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-leader-elector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-leader-elector
subjects:
  - kind: ServiceAccount
    name: service-leader-elector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-leader-elector
  labels:
    app: service-leader-elector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-leader-elector
  template:
    metadata:
      labels:
        app: service-leader-elector
    spec:
      serviceAccountName: service-leader-elector
      containers:
        - name: service-leader-elector
          image: ghcr.io/chia-network/service-leader-elector:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
